Added optional build with mbedtls over boringssl.
Quicr/libquicr pull request #171
Opened 2024-06-14 22:38 UTC by BrettRegnier

Additionally: 'Fixed' compile error saying that fake_transport function setDataCtxPriority doesn't override anything.

Closes #162

2024-07-10 00:37 UTC, TimEvens approved these changes
LGTM, I'll double check and then merge.

2024-07-10 11:06 UTC, RichLogan requested changes
Just noting this here so we don't merge it broken. 

This doesn't work for me out of the box as the python dependency install in transport fails. I think I have a fix in transport though that should work in all cases: https://github.com/Quicr/transport/pull/154

As an aside, should we add a CI variant for an mbedtls build?

2024-07-10 15:40 UTC, RichLogan approved these changes

2024-07-12 22:55 UTC, TimEvens commented
Transport and this branch still depended on the host system having mbedtls and openssl installed. The latest changes resolves it and it builds now in docker where the host/container does not have openssl or mbedtls installed.  

This should be ready to merge.

2024-07-22 16:40 UTC, merged